-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.user_item DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.user_item DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."user";

CREATE TABLE IF NOT EXISTS public."user"
(
    id integer GENERATED ALWAYS NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50) NOT NULL,
    "phone-number" integer NOT NULL,
    email character varying(50) NOT NULL UNIQUE,
    img text,
    "google-id" text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."user"
    IS 'this is the table for the users. ';

DROP TABLE IF EXISTS public.item;

CREATE TABLE IF NOT EXISTS public.item
(
    id integer GENERATED ALWAYS NOT NULL ,
    name character varying(50) NOT NULL,
    price money NOT NULL,
    description text,
    PRIMARY KEY (id, "id-user")
);

COMMENT ON TABLE public.item
    IS 'this is the table that would include all the items that are going to be sold. ';

DROP TABLE IF EXISTS public.user_item;

CREATE TABLE IF NOT EXISTS public.user_item
(
    user_id integer NOT NULL,
    item_id integer NOT NULL
);

DROP TABLE IF EXISTS public.provincias;

CREATE TABLE IF NOT EXISTS public.provincias
(
    id integer GENERATED ALWAYS NOT NULL,
    name character varying(15) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.provincias
    IS 'this is a list of the provinces in the Dominican Republic';

ALTER TABLE IF EXISTS public.user_item
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_item
    ADD FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;